language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly 
sudo: required
dist: trusty
os:
  - linux
install:
  - sudo apt-get install libcryptsetup-dev

# addons:
#   apt:
#     packages:
#       - libcryptsetup-dev
