language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly 
sudo: required
dist: trusty
os:
  - linux
install:
  - sudo apt-get update
  - sudo apt-get install libcryptsetup-dev
  - which cargo
  - /bin/sh -c "echo $PATH"
script:
  - cargo build --verbose
  - sudo /bin/sh -c "PATH=/home/travis/rust/bin:/usr/bin:/bin:/sbin cargo test --verbose"
# addons:
#   apt:
#     packages:
#       - libcryptsetup-dev
