language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly 
sudo: required
dist: trusty
os:
  - linux
install:
  - sudo apt-get update
  - sudo apt-get install libcryptsetup-dev
script:
  - cargo build --verbose
  - sudo -E cargo test --verbose
# addons:
#   apt:
#     packages:
#       - libcryptsetup-dev
