[package]
name = "peroxide-cryptsetup"
version = "0.1.0"
authors = ["Vladimir Lushnikov <vladimir@solidninja.is>"]
build = "build.rs"

[features]
default = ["yubikey", "yubikey_hybrid"]
yubikey = ["ykpers-rs"]
yubikey_hybrid = ["yubikey", "sodiumoxide"]

[build-dependencies]
syntex = "0.52"
serde_codegen = { version = "0.8", features = ["with-syntex"] }

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
serde = "0.8"
serde_json = "0.8"
uuid = { version = "0.3", features = ["serde", "v4"] }
errno = "0.2"
sodiumoxide = { version = "0.0", optional = true }

# TODO - decide on what logger to use :)
log = "0.3"
env_logger = "0.3"
termios = "0.2"
libc = "0.2"

cryptsetup-rs = { version = "0.1.0", path = "lib/cryptsetup-rs" }
ykpers-rs = { version = "0.1.0", path = "lib/ykpers-rs", optional = true }

[dev-dependencies]
tempfile = "2"
tempdir = "0.3"
env_logger = "0.3"
expectest = "0.6"

[lib]
name = "peroxide_cryptsetup"
path = "src/lib/lib.rs"

[[bin]]
name = "peroxs"
test = false
doc = false

[[test]]
name = "tests"

[profile.dev]
codegen-units = 4

[profile.test]
codegen-units = 4
